# Generated by Django 5.0.6 on 2024-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
