# Generated by Django 5.0.6 on 2024-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_driver_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='level',
            field=models.CharField(default='3', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
