# Generated by Django 5.0.6 on 2024-07-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(blank=True, default='Parcel-item', max_length=100, null=True),
        ),
    ]
